export {
  dashboardService,
  DashboardService,
  DateRange,
  DateRangePeriod,
  TrendIndicator,
  MetricsWithTrend,
  WidgetLayout,
  ExportResult,
  CompanyMetrics,
  ClientPipelineMetrics,
  ProjectStatusMetrics,
  PaymentMetrics,
  TeamPerformanceMetrics,
  PropertyMetrics,
  // Role-specific dashboard types
  SecurityAlert,
  PendingApprovalItem,
  CEODashboard,
  FinancialApprovalItem,
  ExecutiveDashboard,
  DepartmentMetric,
  CLevelDashboard,
  LeadItem,
  OperationsDashboard,
  GitHubActivity,
  DeveloperStat,
  TechnologyDashboard,
  AgentCommission,
  AgentDashboard,
  TrainingAssignment,
  TrainerDashboard,
  RoleDashboard,
} from './dashboardService';

export { default as dashboardRoutes } from './dashboardRoutes';
