/**
 * Unit tests for Reporting and Export System
 * Task 21.3: Write unit tests for reporting
 * Requirements: 40.1-40.11
 *
 * Covers:
 *  - Report generation in PDF, Excel (XLSX), and CSV formats (40.1)
 *  - Metadata inclusion: generation date, generated by, filters applied (40.3)
 *  - Export size limits: >10,000 records triggers async processing (40.6-40.8)
 *  - Asynchronous processing with email notification (40.8-40.9)
 *  - Export file retention (40.10)
 *  - Audit logging of exports (40.11)
 */

// ---------------------------------------------------------------------------
// Mocks (must be declared before imports)
// ---------------------------------------------------------------------------

jest.mock('../database/connection', () => ({
  db: { query: jest.fn() },
}));

jest.mock('../utils/logger', () => ({
  __esModule: true,
  default: { info: jest.fn(), warn: jest.fn(), error: jest.fn(), debug: jest.fn() },
}));

jest.mock('../audit/auditService', () => ({
  auditService: { log: jest.fn().mockResolvedValue(undefined) },
  AuditAction: { EXPORT: 'EXPORT' },
  AuditResult: { SUCCESS: 'SUCCESS', FAILURE: 'FAILURE' },
}));

jest.mock('../files/fileService', () => ({
  fileStorageService: {
    uploadFile: jest.fn(),
    deleteFile: jest.fn(),
  },
}));

jest.mock('./exportQueue', () => ({
  exportQueue: { add: jest.fn().mockResolvedValue({ id: 'bull-job-1' }) },
}));

jest.mock('@sendgrid/mail', () => ({
  setApiKey: jest.fn(),
  send: jest.fn().mockResolvedValue([{ statusCode: 202 }]),
}));

// ---------------------------------------------------------------------------
// Imports
// ---------------------------------------------------------------------------

import {
  ReportGenerationService,
  ReportType,
  ReportFilters,
  GeneratedReport,
  ColumnDefinition,
  ReportMetadata,
} from './reportGenerationService';
import {
  AsyncExportService,
  ASYNC_EXPORT_THRESHOLD,
  EXPORT_RETENTION_DAYS,
} from './asyncExportService';
import { db } from '../database/connection';
import { fileStorageService } from '../files/fileService';
import { auditService, AuditResult } from '../audit/auditService';

const mockQuery = db.query as jest.Mock;
const mockUploadFile = fileStorageService.uploadFile as jest.Mock;
const mockDeleteFile = fileStorageService.deleteFile as jest.Mock;
const mockAuditLog = auditService.log as jest.Mock;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function makeColumns(): ColumnDefinition[] {
  return [
    { key: 'id', header: 'ID', width: 10 },
    { key: 'name', header: 'Name', width: 25 },
    { key: 'amount', header: 'Amount', width: 15, type: 'currency' },
    { key: 'created_at', header: 'Created At', width: 22, type: 'date' },
  ];
}

function makeGeneratedReport(
  totalRecords: number,
  filters: ReportFilters = {},
  generatedBy = 'user-test'
): GeneratedReport {
  const metadata: ReportMetadata = {
    reportType: ReportType.CLIENT_LIST,
    generatedAt: new Date('2024-06-01T10:00:00Z'),
    generatedBy,
    filtersApplied: filters,
    totalRecords,
  };
  const data = Array.from({ length: totalRecords }, (_, i) => ({
    id: `rec-${i}`,
    name: `Record ${i}`,
    amount: i * 100,
    created_at: new Date('2024-06-01'),
  }));
  return { metadata, data, columns: makeColumns() };
}

// ===========================================================================
// 1. Report Generation in Multiple Formats (Requirement 40.1)
// ===========================================================================

describe('Report generation in multiple formats (Requirement 40.1)', () => {
  let service: ReportGenerationService;

  beforeEach(() => {
    service = new ReportGenerationService();
    jest.clearAllMocks();
  });

  // ── CSV format ─────────────────────────────────────────────────────────────

  describe('CSV format', () => {
    it('generates a non-empty CSV string', () => {
      const report = makeGeneratedReport(3);
      const csv = service.generateCSV(report);
      expect(typeof csv).toBe('string');
      expect(csv.length).toBeGreaterThan(0);
    });

    it('CSV contains a header row with column names', () => {
      const report = makeGeneratedReport(1);
      const csv = service.generateCSV(report);
      expect(csv).toContain('"ID"');
      expect(csv).toContain('"Name"');
      expect(csv).toContain('"Amount"');
      expect(csv).toContain('"Created At"');
    });

    it('CSV has one data row per record', () => {
      const report = makeGeneratedReport(5);
      const csv = service.generateCSV(report);
      const dataLines = csv.split('\n').filter((l) => !l.startsWith('#') && l.trim() !== '');
      // 1 header + 5 data rows
      expect(dataLines).toHaveLength(6);
    });

    it('CSV handles empty dataset gracefully', () => {
      const report = makeGeneratedReport(0);
      const csv = service.generateCSV(report);
      const dataLines = csv.split('\n').filter((l) => !l.startsWith('#') && l.trim() !== '');
      // Only header row
      expect(dataLines).toHaveLength(1);
    });

    it('CSV formats date columns as ISO strings', () => {
      const report = makeGeneratedReport(1);
      const csv = service.generateCSV(report);
      expect(csv).toContain('2024-06-01');
    });

    it('CSV escapes double quotes in values', () => {
      const report = makeGeneratedReport(0);
      report.data = [{ id: 'x', name: 'He said "hello"', amount: 0, created_at: null }];
      report.metadata.totalRecords = 1;
      const csv = service.generateCSV(report);
      expect(csv).toContain('He said ""hello""');
    });

    it('CSV handles null/undefined values as empty strings', () => {
      const report = makeGeneratedReport(0);
      report.data = [{ id: null, name: undefined, amount: null, created_at: null }];
      report.metadata.totalRecords = 1;
      const csv = service.generateCSV(report);
      const dataLines = csv.split('\n').filter((l) => !l.startsWith('#') && l.trim() !== '');
      const dataRow = dataLines[dataLines.length - 1];
      expect(dataRow).toBe('"","","",""');
    });
  });

  // ── Excel (XLSX) format ────────────────────────────────────────────────────

  describe('Excel (XLSX) format', () => {
    it('generates a Buffer', async () => {
      const report = makeGeneratedReport(3);
      const buffer = await service.generateExcel(report);
      expect(Buffer.isBuffer(buffer)).toBe(true);
    });

    it('XLSX buffer is non-empty', async () => {
      const report = makeGeneratedReport(3);
      const buffer = await service.generateExcel(report);
      expect(buffer.length).toBeGreaterThan(0);
    });

    it('XLSX buffer starts with ZIP magic bytes (PK header)', async () => {
      const report = makeGeneratedReport(2);
      const buffer = await service.generateExcel(report);
      // XLSX files are ZIP archives; magic bytes are 0x50 0x4B
      expect(buffer[0]).toBe(0x50);
      expect(buffer[1]).toBe(0x4b);
    });

    it('handles empty dataset without throwing', async () => {
      const report = makeGeneratedReport(0);
      await expect(service.generateExcel(report)).resolves.not.toThrow();
    });

    it('handles large dataset (1000 rows) without throwing', async () => {
      const report = makeGeneratedReport(1000);
      const buffer = await service.generateExcel(report);
      expect(Buffer.isBuffer(buffer)).toBe(true);
    });
  });

  // ── PDF format (HTML builder) ──────────────────────────────────────────────

  describe('PDF format (HTML builder)', () => {
    it('buildReportHTML returns valid HTML with DOCTYPE', () => {
      const report = makeGeneratedReport(2);
      const html = service.buildReportHTML(report);
      expect(html).toContain('<!DOCTYPE html>');
      expect(html).toContain('<html>');
      expect(html).toContain('</html>');
    });

    it('buildReportHTML includes a table with headers', () => {
      const report = makeGeneratedReport(2);
      const html = service.buildReportHTML(report);
      expect(html).toContain('<table>');
      expect(html).toContain('<th>Name</th>');
      expect(html).toContain('<th>Amount</th>');
    });

    it('buildReportHTML includes TechSwiftTrix branding', () => {
      const report = makeGeneratedReport(1);
      const html = service.buildReportHTML(report);
      expect(html).toContain('TechSwiftTrix');
    });

    it('buildReportHTML renders all data rows', () => {
      const report = makeGeneratedReport(3);
      const html = service.buildReportHTML(report);
      expect(html).toContain('Record 0');
      expect(html).toContain('Record 1');
      expect(html).toContain('Record 2');
    });

    it('buildReportHTML includes report type in heading', () => {
      const report = makeGeneratedReport(0);
      const html = service.buildReportHTML(report);
      expect(html).toContain('CLIENT LIST');
    });
  });

  // ── generateReport supports all 7 types ───────────────────────────────────

  describe('generateReport supports all report types', () => {
    it('supports all 7 report types', async () => {
      const types = Object.values(ReportType);
      expect(types).toHaveLength(7);

      for (const type of types) {
        mockQuery.mockResolvedValueOnce({ rows: [], rowCount: 0 });
        const result = await service.generateReport(type, {}, 'user-1');
        expect(result.metadata.reportType).toBe(type);
      }
    });

    it('throws for unknown report type', async () => {
      await expect(
        service.generateReport('UNKNOWN' as ReportType, {}, 'user-1')
      ).rejects.toThrow('Unknown report type');
    });
  });
});

// ===========================================================================
// 2. Metadata Inclusion (Requirements 40.2, 40.3)
// ===========================================================================

describe('Metadata inclusion in reports (Requirements 40.2, 40.3)', () => {
  let service: ReportGenerationService;

  beforeEach(() => {
    service = new ReportGenerationService();
    jest.clearAllMocks();
    mockQuery.mockResolvedValue({ rows: [], rowCount: 0 });
  });

  it('generateReport includes reportType in metadata', async () => {
    const result = await service.generateReport(ReportType.CLIENT_LIST, {}, 'user-1');
    expect(result.metadata.reportType).toBe(ReportType.CLIENT_LIST);
  });

  it('generateReport includes generatedAt timestamp in metadata', async () => {
    const before = new Date();
    const result = await service.generateReport(ReportType.PAYMENT_SUMMARY, {}, 'user-1');
    const after = new Date();
    expect(result.metadata.generatedAt).toBeInstanceOf(Date);
    expect(result.metadata.generatedAt.getTime()).toBeGreaterThanOrEqual(before.getTime());
    expect(result.metadata.generatedAt.getTime()).toBeLessThanOrEqual(after.getTime());
  });

  it('generateReport includes generatedBy in metadata', async () => {
    const result = await service.generateReport(ReportType.PROJECT_STATUS, {}, 'analyst-42');
    expect(result.metadata.generatedBy).toBe('analyst-42');
  });

  it('generateReport includes filtersApplied in metadata', async () => {
    const filters: ReportFilters = { status: 'LEAD', country: 'Kenya' };
    const result = await service.generateReport(ReportType.CLIENT_LIST, filters, 'user-1');
    expect(result.metadata.filtersApplied).toEqual(filters);
  });

  it('generateReport includes totalRecords count in metadata', async () => {
    mockQuery.mockResolvedValueOnce({ rows: [{ id: 1 }, { id: 2 }, { id: 3 }], rowCount: 3 });
    const result = await service.generateReport(ReportType.CLIENT_LIST, {}, 'user-1');
    expect(result.metadata.totalRecords).toBe(3);
  });

  it('CSV export includes metadata comment lines', () => {
    const filters: ReportFilters = { status: 'COMPLETED', country: 'Nigeria' };
    const report = makeGeneratedReport(2, filters, 'cfo-user');
    const csv = service.generateCSV(report);

    expect(csv).toContain('# Report Type: CLIENT_LIST');
    expect(csv).toContain('# Generated At:');
    expect(csv).toContain('# Generated By: cfo-user');
    expect(csv).toContain('# Filters Applied:');
    expect(csv).toContain('# Total Records: 2');
  });

  it('CSV metadata includes filter values', () => {
    const filters: ReportFilters = { status: 'LEAD', country: 'Ghana' };
    const report = makeGeneratedReport(1, filters, 'user-1');
    const csv = service.generateCSV(report);
    expect(csv).toContain('LEAD');
    expect(csv).toContain('Ghana');
  });

  it('HTML report includes metadata: generatedBy, totalRecords, filters', () => {
    const filters: ReportFilters = { status: 'ACTIVE' };
    const report = makeGeneratedReport(5, filters, 'ceo-user');
    const html = service.buildReportHTML(report);

    expect(html).toContain('Generated By: ceo-user');
    expect(html).toContain('Records: 5');
    expect(html).toContain('status: ACTIVE');
  });

  it('HTML report shows "None" when no filters applied', () => {
    const report = makeGeneratedReport(0, {}, 'user-1');
    const html = service.buildReportHTML(report);
    expect(html).toContain('Filters: None');
  });
});

// ===========================================================================
// 3. Export Size Limits (Requirements 40.6, 40.7)
// ===========================================================================

describe('Export size limits (Requirements 40.6, 40.7)', () => {
  let service: AsyncExportService;

  // For AsyncExportService tests we need to mock reportGenerationService
  // We use jest.spyOn on the singleton after importing it
  let mockGenReport: jest.SpyInstance;

  beforeEach(async () => {
    service = new AsyncExportService();
    jest.clearAllMocks();
    const { reportGenerationService } = await import('./reportGenerationService');
    mockGenReport = jest.spyOn(reportGenerationService, 'generateReport');
  });

  afterEach(() => {
    mockGenReport?.mockRestore();
  });

  it('ASYNC_EXPORT_THRESHOLD is 10,000 records', () => {
    expect(ASYNC_EXPORT_THRESHOLD).toBe(10000);
  });

  it('exports with exactly 10,000 records are processed synchronously', async () => {
    mockGenReport.mockResolvedValue(makeGeneratedReport(10000));
    mockUploadFile.mockResolvedValue({ url: 'https://storage.example.com/file.csv' });
    mockQuery
      .mockResolvedValueOnce({ rows: [{ id: 'job-sync' }] })
      .mockResolvedValueOnce({ rows: [] });

    const result = await service.requestExport(
      ReportType.CLIENT_LIST, 'csv', {}, 'user-1', 'user@example.com'
    );

    expect(result.async).toBe(false);
    expect(result.fileUrl).toBeDefined();
  });

  it('exports with 10,001 records are processed asynchronously', async () => {
    mockGenReport.mockResolvedValue(makeGeneratedReport(10001));
    mockQuery.mockResolvedValueOnce({ rows: [{ id: 'job-async' }] });

    const result = await service.requestExport(
      ReportType.CLIENT_LIST, 'xlsx', {}, 'user-1', 'user@example.com'
    );

    expect(result.async).toBe(true);
    expect(result.fileUrl).toBeUndefined();
  });

  it('exports with 50,000 records are processed asynchronously', async () => {
    mockGenReport.mockResolvedValue(makeGeneratedReport(50000));
    mockQuery.mockResolvedValueOnce({ rows: [{ id: 'job-large' }] });

    const result = await service.requestExport(
      ReportType.PAYMENT_SUMMARY, 'pdf', {}, 'user-1', 'user@example.com'
    );

    expect(result.async).toBe(true);
  });

  it('async export response message mentions the user email', async () => {
    mockGenReport.mockResolvedValue(makeGeneratedReport(20000));
    mockQuery.mockResolvedValueOnce({ rows: [{ id: 'job-email' }] });

    const result = await service.requestExport(
      ReportType.CLIENT_LIST, 'csv', {}, 'user-1', 'analyst@company.com'
    );

    expect(result.message).toContain('analyst@company.com');
  });

  it('async export inserts job with PENDING status', async () => {
    mockGenReport.mockResolvedValue(makeGeneratedReport(15000));
    mockQuery.mockResolvedValueOnce({ rows: [{ id: 'job-pending' }] });

    await service.requestExport(ReportType.CLIENT_LIST, 'csv', {}, 'user-1', 'u@e.com');

    const [insertSql] = mockQuery.mock.calls[0];
    expect(insertSql).toContain("'PENDING'");
  });

  it('sync export inserts job with PROCESSING status', async () => {
    mockGenReport.mockResolvedValue(makeGeneratedReport(100));
    mockUploadFile.mockResolvedValue({ url: 'https://storage.example.com/f.csv' });
    mockQuery
      .mockResolvedValueOnce({ rows: [{ id: 'job-proc' }] })
      .mockResolvedValueOnce({ rows: [] });

    await service.requestExport(ReportType.CLIENT_LIST, 'csv', {}, 'user-1', 'u@e.com');

    const [insertSql] = mockQuery.mock.calls[0];
    expect(insertSql).toContain("'PROCESSING'");
  });
});

// ===========================================================================
// 4. Asynchronous Processing (Requirements 40.8, 40.9)
// ===========================================================================

describe('Asynchronous export processing (Requirements 40.8, 40.9)', () => {
  let service: AsyncExportService;
  let mockGenReport: jest.SpyInstance;

  beforeEach(async () => {
    service = new AsyncExportService();
    jest.clearAllMocks();
    const { reportGenerationService } = await import('./reportGenerationService');
    mockGenReport = jest.spyOn(reportGenerationService, 'generateReport');
  });

  afterEach(() => {
    mockGenReport?.mockRestore();
  });

  it('queues job to Bull when export exceeds threshold', async () => {
    mockGenReport.mockResolvedValue(makeGeneratedReport(12000));
    mockQuery.mockResolvedValueOnce({ rows: [{ id: 'job-q' }] });

    await service.requestExport(ReportType.CLIENT_LIST, 'xlsx', {}, 'user-1', 'u@e.com');

    const { exportQueue } = await import('./exportQueue');
    expect(exportQueue.add).toHaveBeenCalledWith(
      { jobId: 'job-q', userEmail: 'u@e.com' },
      expect.objectContaining({ attempts: 3 })
    );
  });

  it('processExportJob transitions status: PROCESSING → COMPLETED', async () => {
    const jobRow = { user_id: 'user-1', report_type: 'CLIENT_LIST', format: 'csv', filters: '{}' };
    mockGenReport.mockResolvedValue(makeGeneratedReport(500));
    mockUploadFile.mockResolvedValue({ url: 'https://storage.example.com/export.csv' });
    mockQuery
      .mockResolvedValueOnce({ rows: [] })
      .mockResolvedValueOnce({ rows: [jobRow] })
      .mockResolvedValueOnce({ rows: [] });

    await service.processExportJob('job-1', 'user@example.com');

    const [processSql] = mockQuery.mock.calls[0];
    const [completeSql] = mockQuery.mock.calls[2];
    expect(processSql).toContain("'PROCESSING'");
    expect(completeSql).toContain("'COMPLETED'");
  });

  it('processExportJob stores file URL in job record', async () => {
    const jobRow = { user_id: 'user-1', report_type: 'CLIENT_LIST', format: 'xlsx', filters: '{}' };
    mockGenReport.mockResolvedValue(makeGeneratedReport(200));
    mockUploadFile.mockResolvedValue({ url: 'https://storage.example.com/report.xlsx' });
    mockQuery
      .mockResolvedValueOnce({ rows: [] })
      .mockResolvedValueOnce({ rows: [jobRow] })
      .mockResolvedValueOnce({ rows: [] });

    await service.processExportJob('job-2', 'user@example.com');

    const [, completeParams] = mockQuery.mock.calls[2];
    expect(completeParams[0]).toBe('https://storage.example.com/report.xlsx');
  });

  it('processExportJob marks job as FAILED on error', async () => {
    const jobRow = { user_id: 'user-1', report_type: 'CLIENT_LIST', format: 'csv', filters: '{}' };
    mockQuery
      .mockResolvedValueOnce({ rows: [] })
      .mockResolvedValueOnce({ rows: [jobRow] })
      .mockResolvedValueOnce({ rows: [] });
    mockGenReport.mockRejectedValueOnce(new Error('DB timeout'));

    await expect(service.processExportJob('job-fail', 'u@e.com')).rejects.toThrow('DB timeout');

    const [failSql] = mockQuery.mock.calls[2];
    expect(failSql).toContain("'FAILED'");
  });

  it('processExportJob throws when job is not found', async () => {
    mockQuery
      .mockResolvedValueOnce({ rows: [] })
      .mockResolvedValueOnce({ rows: [] });

    await expect(service.processExportJob('missing', 'u@e.com')).rejects.toThrow('not found');
  });

  it('processExportJob sends email notification on completion (Requirement 40.9)', async () => {
    const sgMail = require('@sendgrid/mail');
    process.env.SENDGRID_API_KEY = 'test-key';

    const jobRow = { user_id: 'user-1', report_type: 'CLIENT_LIST', format: 'csv', filters: '{}' };
    mockGenReport.mockResolvedValue(makeGeneratedReport(100));
    mockUploadFile.mockResolvedValue({ url: 'https://storage.example.com/file.csv' });
    mockQuery
      .mockResolvedValueOnce({ rows: [] })
      .mockResolvedValueOnce({ rows: [jobRow] })
      .mockResolvedValueOnce({ rows: [] });

    await service.processExportJob('job-email', 'recipient@example.com');

    expect(sgMail.send).toHaveBeenCalledWith(
      expect.objectContaining({ to: 'recipient@example.com' })
    );

    delete process.env.SENDGRID_API_KEY;
  });

  it('getExportStatus returns null for unknown job', async () => {
    mockQuery.mockResolvedValueOnce({ rows: [] });
    const result = await service.getExportStatus('unknown-job');
    expect(result).toBeNull();
  });

  it('getExportStatus returns job details for known job', async () => {
    mockQuery.mockResolvedValueOnce({
      rows: [{
        id: 'job-known',
        user_id: 'user-1',
        report_type: 'CLIENT_LIST',
        format: 'csv',
        filters: '{}',
        status: 'COMPLETED',
        file_url: 'https://storage.example.com/file.csv',
        error_message: null,
        created_at: new Date('2024-01-01'),
        completed_at: new Date('2024-01-01T01:00:00Z'),
        expires_at: new Date('2024-01-08'),
      }],
    });

    const job = await service.getExportStatus('job-known');
    expect(job).not.toBeNull();
    expect(job!.status).toBe('COMPLETED');
    expect(job!.fileUrl).toBe('https://storage.example.com/file.csv');
  });
});

// ===========================================================================
// 5. Export File Retention and Cleanup (Requirement 40.10)
// ===========================================================================

describe('Export file retention (Requirement 40.10)', () => {
  let service: AsyncExportService;

  beforeEach(() => {
    service = new AsyncExportService();
    jest.clearAllMocks();
  });

  it('EXPORT_RETENTION_DAYS is 7', () => {
    expect(EXPORT_RETENTION_DAYS).toBe(7);
  });

  it('cleanupExpiredExports returns 0 when no expired jobs', async () => {
    mockQuery.mockResolvedValueOnce({ rows: [] });
    const count = await service.cleanupExpiredExports();
    expect(count).toBe(0);
  });

  it('cleanupExpiredExports deletes expired job records', async () => {
    mockQuery
      .mockResolvedValueOnce({ rows: [{ id: 'old-job', file_url: null }] })
      .mockResolvedValueOnce({ rows: [] });

    const count = await service.cleanupExpiredExports();
    expect(count).toBe(1);

    const [deleteSql] = mockQuery.mock.calls[1];
    expect(deleteSql).toContain('DELETE FROM export_jobs');
  });

  it('cleanupExpiredExports deletes storage file when file_url is present', async () => {
    mockQuery
      .mockResolvedValueOnce({
        rows: [{
          id: 'old-job',
          file_url: 'https://s3.example.com/reports/abc123def456abc123def456abc123de/file.csv',
        }],
      })
      .mockResolvedValueOnce({ rows: [] });

    mockDeleteFile.mockResolvedValueOnce(undefined);

    await service.cleanupExpiredExports();
    expect(mockDeleteFile).toHaveBeenCalledTimes(1);
  });

  it('cleanupExpiredExports handles multiple expired jobs', async () => {
    mockQuery
      .mockResolvedValueOnce({
        rows: [
          { id: 'job-1', file_url: null },
          { id: 'job-2', file_url: null },
          { id: 'job-3', file_url: null },
        ],
      })
      .mockResolvedValueOnce({ rows: [] })
      .mockResolvedValueOnce({ rows: [] })
      .mockResolvedValueOnce({ rows: [] });

    const count = await service.cleanupExpiredExports();
    expect(count).toBe(3);
  });

  it('cleanupExpiredExports continues even if one file deletion fails', async () => {
    mockQuery
      .mockResolvedValueOnce({
        rows: [
          { id: 'job-a', file_url: 'https://s3.example.com/reports/abc123def456abc123def456abc123de/a.csv' },
          { id: 'job-b', file_url: null },
        ],
      })
      .mockResolvedValueOnce({ rows: [] })
      .mockResolvedValueOnce({ rows: [] });

    mockDeleteFile.mockRejectedValueOnce(new Error('S3 error'));

    const count = await service.cleanupExpiredExports();
    expect(count).toBe(2);
  });
});

// ===========================================================================
// 6. Audit Logging of Exports (Requirement 40.11)
// ===========================================================================

describe('Audit logging of exports (Requirement 40.11)', () => {
  let service: AsyncExportService;
  let mockGenReport: jest.SpyInstance;

  beforeEach(async () => {
    service = new AsyncExportService();
    jest.clearAllMocks();
    const { reportGenerationService } = await import('./reportGenerationService');
    mockGenReport = jest.spyOn(reportGenerationService, 'generateReport');
  });

  afterEach(() => {
    mockGenReport?.mockRestore();
  });

  it('logs export operation to audit log for synchronous export', async () => {
    mockGenReport.mockResolvedValue(makeGeneratedReport(50));
    mockUploadFile.mockResolvedValue({ url: 'https://storage.example.com/f.csv' });
    mockQuery
      .mockResolvedValueOnce({ rows: [{ id: 'job-audit-sync' }] })
      .mockResolvedValueOnce({ rows: [] });

    await service.requestExport(ReportType.CLIENT_LIST, 'csv', {}, 'user-audit', 'u@e.com');

    expect(mockAuditLog).toHaveBeenCalledWith(
      expect.objectContaining({
        userId: 'user-audit',
        resourceType: 'export_job',
      })
    );
  });

  it('logs export operation to audit log for asynchronous export', async () => {
    mockGenReport.mockResolvedValue(makeGeneratedReport(20000));
    mockQuery.mockResolvedValueOnce({ rows: [{ id: 'job-audit-async' }] });

    await service.requestExport(ReportType.CLIENT_LIST, 'xlsx', {}, 'user-audit', 'u@e.com');

    expect(mockAuditLog).toHaveBeenCalledWith(
      expect.objectContaining({
        userId: 'user-audit',
        resourceType: 'export_job',
        resourceId: 'job-audit-async',
      })
    );
  });

  it('logs export failure to audit log when processExportJob fails', async () => {
    const jobRow = { user_id: 'user-1', report_type: 'CLIENT_LIST', format: 'csv', filters: '{}' };
    mockQuery
      .mockResolvedValueOnce({ rows: [] })
      .mockResolvedValueOnce({ rows: [jobRow] })
      .mockResolvedValueOnce({ rows: [] });
    mockGenReport.mockRejectedValueOnce(new Error('Failure'));

    await expect(service.processExportJob('job-fail-audit', 'u@e.com')).rejects.toThrow();

    expect(mockAuditLog).toHaveBeenCalledWith(
      expect.objectContaining({ result: AuditResult.FAILURE })
    );
  });
});
