import {
  ReportGenerationService,
  ReportType,
  ReportFilters,
  GeneratedReport,
  ColumnDefinition,
  ReportMetadata,
} from './reportGenerationService';

// Mock the database so tests don't need a real DB connection
jest.mock('../database/connection', () => ({
  db: {
    query: jest.fn(),
  },
}));

jest.mock('../utils/logger', () => ({
  info: jest.fn(),
  error: jest.fn(),
  warn: jest.fn(),
  debug: jest.fn(),
}));

import { db } from '../database/connection';
const mockDb = db as jest.Mocked<typeof db>;

// ─── Helpers ──────────────────────────────────────────────────────────────────

function makeReport(
  type: ReportType = ReportType.CLIENT_LIST,
  data: Record<string, any>[] = [],
  filters: ReportFilters = {}
): GeneratedReport {
  const columns: ColumnDefinition[] = [
    { key: 'name', header: 'Name', width: 25 },
    { key: 'status', header: 'Status', width: 20 },
    { key: 'amount', header: 'Amount', width: 15, type: 'currency' },
    { key: 'created_at', header: 'Created At', width: 22, type: 'date' },
  ];
  const metadata: ReportMetadata = {
    reportType: type,
    generatedAt: new Date('2024-06-01T10:00:00Z'),
    generatedBy: 'user-123',
    filtersApplied: filters,
    totalRecords: data.length,
  };
  return { metadata, data, columns };
}

// ─── Tests ────────────────────────────────────────────────────────────────────

describe('ReportGenerationService', () => {
  let service: ReportGenerationService;

  beforeEach(() => {
    service = new ReportGenerationService();
    jest.clearAllMocks();
  });

  // ─── generateReport ────────────────────────────────────────────────────────

  describe('generateReport', () => {
    it('returns metadata with reportType, generatedAt, generatedBy, filtersApplied, totalRecords', async () => {
      mockDb.query.mockResolvedValueOnce({ rows: [{ name: 'Test Client' }], rowCount: 1 } as any);

      const filters: ReportFilters = { status: 'LEAD' };
      const result = await service.generateReport(ReportType.CLIENT_LIST, filters, 'user-123');

      expect(result.metadata.reportType).toBe(ReportType.CLIENT_LIST);
      expect(result.metadata.generatedBy).toBe('user-123');
      expect(result.metadata.filtersApplied).toEqual(filters);
      expect(result.metadata.generatedAt).toBeInstanceOf(Date);
      expect(result.metadata.totalRecords).toBe(1);
    });

    it('returns columns for the report type', async () => {
      mockDb.query.mockResolvedValueOnce({ rows: [], rowCount: 0 } as any);

      const result = await service.generateReport(ReportType.PROJECT_STATUS, {}, 'user-1');

      expect(Array.isArray(result.columns)).toBe(true);
      expect(result.columns.length).toBeGreaterThan(0);
      expect(result.columns[0]).toHaveProperty('key');
      expect(result.columns[0]).toHaveProperty('header');
    });

    it('throws for unknown report type', async () => {
      await expect(
        service.generateReport('UNKNOWN' as ReportType, {}, 'user-1')
      ).rejects.toThrow('Unknown report type');
    });

    it('passes date filters to the query', async () => {
      mockDb.query.mockResolvedValueOnce({ rows: [], rowCount: 0 } as any);

      const filters: ReportFilters = {
        dateFrom: new Date('2024-01-01'),
        dateTo: new Date('2024-12-31'),
      };
      await service.generateReport(ReportType.PAYMENT_SUMMARY, filters, 'user-1');

      const callArgs = mockDb.query.mock.calls[0];
      expect(callArgs[1]).toContain(filters.dateFrom);
      expect(callArgs[1]).toContain(filters.dateTo);
    });

    it('supports all 7 report types', async () => {
      const types = Object.values(ReportType);
      expect(types).toHaveLength(7);

      for (const type of types) {
        mockDb.query.mockResolvedValueOnce({ rows: [], rowCount: 0 } as any);
        const result = await service.generateReport(type, {}, 'user-1');
        expect(result.metadata.reportType).toBe(type);
      }
    });
  });

  // ─── generateCSV ──────────────────────────────────────────────────────────

  describe('generateCSV', () => {
    it('includes metadata comment lines at the top', () => {
      const report = makeReport(ReportType.CLIENT_LIST, [], { status: 'LEAD' });
      const csv = service.generateCSV(report);

      expect(csv).toContain('# Report Type: CLIENT_LIST');
      expect(csv).toContain('# Generated At:');
      expect(csv).toContain('# Generated By: user-123');
      expect(csv).toContain('# Filters Applied:');
      expect(csv).toContain('# Total Records: 0');
    });

    it('includes a header row with column names', () => {
      const report = makeReport();
      const csv = service.generateCSV(report);

      expect(csv).toContain('"Name"');
      expect(csv).toContain('"Status"');
      expect(csv).toContain('"Amount"');
    });

    it('produces one data row per record', () => {
      const data = [
        { name: 'Alice', status: 'LEAD', amount: 100, created_at: null },
        { name: 'Bob', status: 'PROJECT', amount: 200, created_at: null },
      ];
      const report = makeReport(ReportType.CLIENT_LIST, data);
      const csv = service.generateCSV(report);

      // Count non-comment, non-empty lines
      const dataLines = csv.split('\n').filter((l) => !l.startsWith('#') && l.trim() !== '');
      expect(dataLines).toHaveLength(3); // header + 2 rows
    });

    it('escapes double quotes in values', () => {
      const data = [{ name: 'He said "hello"', status: 'LEAD', amount: 0, created_at: null }];
      const report = makeReport(ReportType.CLIENT_LIST, data);
      const csv = service.generateCSV(report);

      expect(csv).toContain('He said ""hello""');
    });

    it('formats Date objects as ISO strings', () => {
      const date = new Date('2024-06-15T10:00:00Z');
      const data = [{ name: 'Test', status: 'LEAD', amount: 0, created_at: date }];
      const report = makeReport(ReportType.CLIENT_LIST, data);
      const csv = service.generateCSV(report);

      expect(csv).toContain('2024-06-15');
    });

    it('handles null/undefined values as empty strings', () => {
      const data = [{ name: null, status: undefined, amount: null, created_at: null }];
      const report = makeReport(ReportType.CLIENT_LIST, data);
      const csv = service.generateCSV(report);

      const dataLines = csv.split('\n').filter((l) => !l.startsWith('#') && l.trim() !== '');
      // Last line should be the data row with empty values
      const dataRow = dataLines[dataLines.length - 1];
      expect(dataRow).toBe('"","","",""');
    });
  });

  // ─── generateExcel ────────────────────────────────────────────────────────

  describe('generateExcel', () => {
    it('returns a Buffer', async () => {
      const report = makeReport(ReportType.CLIENT_LIST, [{ name: 'Alice', status: 'LEAD', amount: 500, created_at: null }]);
      const buffer = await service.generateExcel(report);

      expect(Buffer.isBuffer(buffer)).toBe(true);
      expect(buffer.length).toBeGreaterThan(0);
    });

    it('produces a valid XLSX file (starts with PK zip header)', async () => {
      const report = makeReport(ReportType.PAYMENT_SUMMARY, [{ name: 'Bob', status: 'COMPLETED', amount: 1000, created_at: null }]);
      const buffer = await service.generateExcel(report);

      // XLSX files are ZIP archives starting with PK (0x50 0x4B)
      expect(buffer[0]).toBe(0x50);
      expect(buffer[1]).toBe(0x4b);
    });

    it('handles empty data', async () => {
      const report = makeReport(ReportType.PROJECT_STATUS, []);
      const buffer = await service.generateExcel(report);

      expect(Buffer.isBuffer(buffer)).toBe(true);
    });
  });

  // ─── buildReportHTML ──────────────────────────────────────────────────────

  describe('buildReportHTML', () => {
    it('includes report type in the output', () => {
      const report = makeReport(ReportType.CLIENT_LIST);
      const html = service.buildReportHTML(report);

      expect(html).toContain('CLIENT LIST');
    });

    it('includes metadata: generatedAt, generatedBy, totalRecords, filters', () => {
      const report = makeReport(ReportType.PAYMENT_SUMMARY, [], { status: 'COMPLETED' });
      const html = service.buildReportHTML(report);

      expect(html).toContain('Generated By: user-123');
      expect(html).toContain('Records: 0');
      expect(html).toContain('status: COMPLETED');
    });

    it('renders table headers', () => {
      const report = makeReport();
      const html = service.buildReportHTML(report);

      expect(html).toContain('<th>Name</th>');
      expect(html).toContain('<th>Status</th>');
    });

    it('renders data rows', () => {
      const data = [
        { name: 'Alpha Corp', status: 'LEAD', amount: 1000, created_at: null },
        { name: 'Beta Ltd', status: 'PROJECT', amount: 2000, created_at: null },
      ];
      const report = makeReport(ReportType.CLIENT_LIST, data);
      const html = service.buildReportHTML(report);

      expect(html).toContain('Alpha Corp');
      expect(html).toContain('Beta Ltd');
    });

    it('returns valid HTML structure', () => {
      const report = makeReport();
      const html = service.buildReportHTML(report);

      expect(html).toContain('<!DOCTYPE html>');
      expect(html).toContain('<html>');
      expect(html).toContain('</html>');
      expect(html).toContain('<table>');
    });

    it('includes TechSwiftTrix branding', () => {
      const report = makeReport();
      const html = service.buildReportHTML(report);

      expect(html).toContain('TechSwiftTrix');
    });
  });

  // ─── Report type coverage ─────────────────────────────────────────────────

  describe('ReportType enum', () => {
    it('defines all 7 required report types', () => {
      expect(ReportType.CLIENT_LIST).toBe('CLIENT_LIST');
      expect(ReportType.LEAD_PIPELINE).toBe('LEAD_PIPELINE');
      expect(ReportType.PROJECT_STATUS).toBe('PROJECT_STATUS');
      expect(ReportType.PAYMENT_SUMMARY).toBe('PAYMENT_SUMMARY');
      expect(ReportType.AUDIT_SUMMARY).toBe('AUDIT_SUMMARY');
      expect(ReportType.ACHIEVEMENT_SUMMARY).toBe('ACHIEVEMENT_SUMMARY');
      expect(ReportType.DAILY_REPORT_COMPLIANCE).toBe('DAILY_REPORT_COMPLIANCE');
    });
  });
});
